#!/usr/bin/env python3
"""Paper 3: macros for the cap sensitivity sweep.

The paper asserts that the regime in which the thermal-aware controller earns
its complexity is narrow, and never measures it. All three earlier TSUSC reviews
asked for a sensitivity analysis. This sweep answers both: seven cap settings
from 46 to 51 C, three policies at each, cap order alternating about the middle
so that cap is not collinear with elapsed time, and the 49 C operating point
measured first and last as a drift check.

The window turns out to be three degrees wide, and both of its edges fail for
different reasons, which is a sharper statement than the paper currently makes.

Outputs paper/numbers_capsweep.tex.
"""
import collections
import json
import os

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(HERE, "data", "paper3_cap_sweep.json")
OUT = os.path.join(HERE, "paper", "numbers_capsweep.tex")

VIOL_OK = 5          # seconds of a 60 s run; above this the cap is not held
ACC_KEEP = 95.0      # percent of always-final accuracy worth keeping

lines = ["% generated by code/fill_capsweep.py -- do not edit"]


def put(name, val):
    lines.append(r"\newcommand{\np%s}{%s}" % (name, val))


runs = json.load(open(SRC))
by = collections.defaultdict(dict)
for r in runs:
    by[(r["cap"], r["run_index"])][r["policy"]] = r

# The repeated 49 C point is the drift check, not a sweep point.
first_key = min(by, key=lambda k: k[1])
last_key = max(by, key=lambda k: k[1])
sweep_keys = sorted(by, key=lambda k: k[0])

rows, winners = [], []
for key in sweep_keys:
    cap = key[0]
    d = by[key]
    e1, fin, ad = d.get("always-exit1"), d.get("always-final"), d.get("adaptive-ctrl")
    if not (e1 and fin and ad):
        continue
    keeps = 100.0 * ad["real_acc"] / fin["real_acc"]
    holds = ad["cap_viol_s"] <= VIOL_OK
    final_violates = fin["cap_viol_s"] > VIOL_OK
    # The controller "pays" only where the cap actually binds something AND it
    # holds the cap AND it keeps most of the accuracy. All three are needed.
    pays = holds and final_violates and keeps >= ACC_KEEP
    winners.append((cap, pays, key[1]))
    rows.append("%.0f & %d & %d & %d & %.2f & %.0f\\%% & %s \\\\" % (
        cap, e1["cap_viol_s"], fin["cap_viol_s"], ad["cap_viol_s"],
        ad["real_acc"], keeps, r"\checkmark" if pays else "--"))

put("TableCapSweep", "%\n" + "\n".join(rows))

paying = sorted({c for c, p, _ in winners if p})
put("CapNSettings", str(len({k[0] for k in sweep_keys})))
put("CapLo", "%.0f" % min(k[0] for k in sweep_keys))
put("CapHi", "%.0f" % max(k[0] for k in sweep_keys))
put("CapNPay", str(len(paying)))
if paying:
    put("CapPayLo", "%.0f" % min(paying))
    put("CapPayHi", "%.0f" % max(paying))
    put("CapWindow", "%.0f" % (max(paying) - min(paying) + 1))

# The slack end: where always-final already complies, the controller has no job.
slack = [(c, by[k]) for c, p, i in winners for k in [(c, i)] if not p
         and by[k]["always-final"]["cap_viol_s"] <= VIOL_OK]
if slack:
    c, d = slack[0]
    put("CapSlack", "%.0f" % c)
    put("CapSlackFinalViol", str(d["always-final"]["cap_viol_s"]))
    put("CapSlackCtrlAcc", "%.2f" % d["adaptive-ctrl"]["real_acc"])
    put("CapSlackFinalAcc", "%.2f" % d["always-final"]["real_acc"])

# The tight end: where even the shallowest exit violates, nothing can help.
tight = [(c, by[k]) for c, p, i in winners for k in [(c, i)] if not p
         and by[k]["always-exit1"]["cap_viol_s"] > VIOL_OK]
if tight:
    c, d = tight[0]
    put("CapTight", "%.0f" % c)
    put("CapTightExitOneViol", str(d["always-exit1"]["cap_viol_s"]))
    put("CapTightCtrlViol", str(d["adaptive-ctrl"]["cap_viol_s"]))
    put("CapTightCtrlAcc", "%.2f" % d["adaptive-ctrl"]["real_acc"])
    put("CapTightCtrlExitOne", "%.1f" % d["adaptive-ctrl"]["exit_mix"].get("exit1", 0.0))

# Drift check: the same cap, same policies, first and last.
a, b = by[first_key], by[last_key]
put("CapDriftCap", "%.0f" % first_key[0])
put("CapDriftExitOneFirst", str(a["always-exit1"]["cap_viol_s"]))
put("CapDriftExitOneLast", str(b["always-exit1"]["cap_viol_s"]))
put("CapDriftTempFirst", "%.1f" % a["always-exit1"]["mean_temp"])
put("CapDriftTempLast", "%.1f" % b["always-exit1"]["mean_temp"])
put("CapDriftCtrlAccFirst", "%.2f" % a["adaptive-ctrl"]["real_acc"])
put("CapDriftCtrlAccLast", "%.2f" % b["adaptive-ctrl"]["real_acc"])

open(OUT, "w").write("\n".join(lines) + "\n")
print("wrote", OUT, "(%d macros)" % (len(lines) - 1))
print("  caps swept: %s" % sorted({k[0] for k in sweep_keys}))
print("  controller pays at: %s  (window %d C of %d settings)"
      % (paying, (max(paying) - min(paying) + 1) if paying else 0,
         len({k[0] for k in sweep_keys})))
for c, p, i in winners:
    d = by[(c, i)]
    print("   cap %.0f  exit1 %3ds | final %3ds | ctrl %3ds @ %.2f%%  -> %s"
          % (c, d["always-exit1"]["cap_viol_s"], d["always-final"]["cap_viol_s"],
             d["adaptive-ctrl"]["cap_viol_s"], d["adaptive-ctrl"]["real_acc"],
             "PAYS" if p else "no"))
print("  drift check at %.0f C: exit1 violations %ds -> %ds, mean temp %.1f -> %.1f"
      % (first_key[0], a["always-exit1"]["cap_viol_s"], b["always-exit1"]["cap_viol_s"],
         a["always-exit1"]["mean_temp"], b["always-exit1"]["mean_temp"]))
