#!/usr/bin/env python3
"""Macros for Paper 3's repetition campaign.

All three TSUSC reviews of the earlier version asked for multi-run statistics
against a single run. Running them did more than add error bars: the five
repetitions land in a different operating regime from the published single run,
at the same mean board temperature, which is a finding about the controller
rather than about noise.

Outputs paper/numbers_reps.tex.
"""
import collections
import json
import os
import statistics as st

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
REPS = json.load(open(os.path.join(HERE, "data", "paper3_controller_reps.json")))
OLD = json.load(open(os.path.join(HERE, "data", "paper3_controller_results.json")))
OUT = os.path.join(HERE, "paper", "numbers_reps.tex")

lines = ["% generated by code/fill_reps.py -- do not edit"]


def put(name, val):
    lines.append(r"\newcommand{\np%s}{%s}" % (name, val))


by = collections.defaultdict(list)
for r in REPS:
    by[r["policy"]].append(r)
old = {x["policy"]: x for x in OLD}


def ms(vals, prec=2):
    if len(vals) < 2:
        return "%.*f" % (prec, vals[0])
    return "%.*f$\\,\\pm\\,$%.*f" % (prec, st.mean(vals), prec, st.stdev(vals))


SHORT = {"always-exit1": "ExitOne", "always-exit2": "ExitTwo",
         "always-final": "Final", "adaptive-ctrl": "Adaptive"}

rows = []
for pol in ("always-exit1", "always-exit2", "always-final", "adaptive-ctrl"):
    v = by[pol]
    tag = SHORT[pol]
    put("%sAcc" % tag, ms([x["real_acc"] for x in v]))
    put("%sPnn" % tag, ms([x["p99"] for x in v], 3))
    put("%sViol" % tag, ms([float(x["cap_viol_s"]) for x in v], 1))
    put("%sTmax" % tag, ms([x["max_temp"] for x in v], 1))
    rows.append("%s & %d & %s & %s & %s & %s \\\\" % (
        pol.replace("_", "\\_"), len(v),
        ms([x["real_acc"] for x in v]),
        ms([x["p50"] for x in v], 3),
        ms([x["p99"] for x in v], 3),
        ms([float(x["cap_viol_s"]) for x in v], 1)))
put("TableReps", "%\n" + "\n".join(rows))

# The regime split: what the repetitions did that the published run did not.
a = by["adaptive-ctrl"]
put("NReps", str(len(a)))
put("RepsExitOneUse", "%.1f" % max(x["exit_mix"].get("exit1", 0.0) for x in a))
put("PubExitOneUse", "%.1f" % old["adaptive-ctrl"]["exit_mix"].get("exit1", 0.0))
put("PubAcc", "%.2f" % old["adaptive-ctrl"]["real_acc"])
put("RepsMeanT", ms([x["mean_temp"] for x in a]))
put("PubMeanT", "%.2f" % old["adaptive-ctrl"]["mean_temp"])
put("RepsStartTLo", "%.1f" % min(x["start_temp"] for x in a))
put("RepsStartTHi", "%.1f" % max(x["start_temp"] for x in a))

# Headline comparison the controller is judged on.
fin = by["always-final"]
e1 = by["always-exit1"]
put("AccRetained", "%.1f" % (
    100 * st.mean([x["real_acc"] for x in a]) / st.mean([x["real_acc"] for x in fin])))
put("ViolCut", "%.0f" % (
    100 * (1 - st.mean([float(x["cap_viol_s"]) for x in a])
           / st.mean([float(x["cap_viol_s"]) for x in fin]))))
put("AccOverExitOne", "%.1f" % (
    st.mean([x["real_acc"] for x in a]) - st.mean([x["real_acc"] for x in e1])))

open(OUT, "w", newline="\n").write("\n".join(lines) + "\n")
print("wrote", OUT, "(%d macros)" % (len(lines) - 1))
for pol in ("always-exit1", "always-exit2", "always-final", "adaptive-ctrl"):
    v = by[pol]
    print("  %-14s n=%d acc=%s viol=%s" % (
        pol, len(v), ms([x["real_acc"] for x in v]),
        ms([float(x["cap_viol_s"]) for x in v], 1)))
