#!/usr/bin/env python3
"""Paper 3: macros for the dead-band sensitivity sweep.

The controller has two parameters. The cap sweep measured one and found a
three-degree window. This varies the other, the dead band, which had been set to
3.0 C once and never questioned, and the answer is negative in a way that is
worth reporting.

Sweeping the band from 1 to 5 C moves accuracy across a range of about eight
points. Measuring the SAME band twice, first and last in the session, moves it
six. The parameter cannot be separated from run-to-run variation, so the band is
not tunable from single runs on this system, and any paper that reported a
tuned value would be reporting a trajectory.

That is the same ratchet the evaluation section describes, arriving for the
third time and now as a limit on what can be tuned rather than on what can be
measured.

Outputs paper/numbers_bandsweep.tex.
"""
import json
import os

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(HERE, "data", "paper3_band_sweep.json")
OUT = os.path.join(HERE, "paper", "numbers_bandsweep.tex")

lines = ["% generated by code/fill_bandsweep.py -- do not edit"]


def put(name, val):
    lines.append(r"\newcommand{\np%s}{%s}" % (name, val))


runs = json.load(open(SRC))
first = [r for r in runs if r["run_index"] == 0][0]
last = [r for r in runs if r.get("is_repeat_reference")][0]
sweep = [r for r in runs if not r.get("is_repeat_reference")]

accs = [r["real_acc"] for r in sweep]
across = max(accs) - min(accs)
within = abs(first["real_acc"] - last["real_acc"])

put("BandLo", "%.0f" % min(r["band"] for r in sweep))
put("BandHi", "%.0f" % max(r["band"] for r in sweep))
put("BandN", str(len(sweep)))
put("BandDefault", "%.0f" % first["band"])
put("BandAccMin", "%.2f" % min(accs))
put("BandAccMax", "%.2f" % max(accs))
put("BandAcross", "%.1f" % across)
put("BandWithin", "%.1f" % within)
put("BandRepeatAccFirst", "%.2f" % first["real_acc"])
put("BandRepeatAccLast", "%.2f" % last["real_acc"])
put("BandRepeatViolFirst", str(first["cap_viol_s"]))
put("BandRepeatViolLast", str(last["cap_viol_s"]))
put("BandRepeatExitOneFirst", "%.0f" % first["exit_mix"].get("exit1", 0.0))
put("BandRepeatExitOneLast", "%.0f" % last["exit_mix"].get("exit1", 0.0))
put("BandRatio", "%.2f" % (within / across) if across else "n/a")

rows = []
for r in sorted(runs, key=lambda r: r["run_index"]):
    rows.append("%.0f & %s & %.2f & %d & %.0f\\%% \\\\" % (
        r["band"], "repeat" if r.get("is_repeat_reference") else str(r["run_index"] + 1),
        r["real_acc"], r["cap_viol_s"], r["exit_mix"].get("exit1", 0.0)))
put("TableBandSweep", "%\n" + "\n".join(rows))

open(OUT, "w", newline="\n").write("\n".join(lines) + "\n")
print("wrote", OUT, "(%d macros)" % (len(lines) - 1))
print("  bands %.0f to %.0f C, accuracy %.2f to %.2f (%.1f points across bands)"
      % (min(r["band"] for r in sweep), max(r["band"] for r in sweep),
         min(accs), max(accs), across))
print("  SAME band %.0f C measured twice: %.2f%% then %.2f%% (%.1f points within one band)"
      % (first["band"], first["real_acc"], last["real_acc"], within))
print("  within/across = %.2f: the band is not separable from run-to-run variation"
      % (within / across if across else float("nan")))
